contact_map_path: /home/joepaggi/share/rcmc/WT_BR1/select_corrected_minus_inward.mcool
region: 'chr5:31,345,000-31,365,000'
max_iter: 10
error_tolerance: 0.00

normalization: 'mask'
normalization_params:
    normalization:
        'max_prob': 0.95
        'neighbor_prob': 0.5
        'bw': 1
    ice:
        'mad_max': 2
        'min_nnz': 100
        'correct_for_flanks': True
    neighbor: True
capture_probes_path: /home/joepaggi/share/rcmc/captureprobes_mm39.bed

smoothing: coarsen

optimizer: 'gradient_descent'
optimizer_params:
    learning_rate: 0.3
    beta: 0.75
    initial_alpha: 0.0
    warmup_t: 5

model: polymer
model_params:
    bond_length: 21
    nucleosome_diameter: 11
    angle_constant: 1.0
    nuc_nuc_attraction: -1.0
    n_dna: 5
    n_cap: 50
    dna_diameter: 5
    terminal_nucleosome_diameter: 300
    nuc_nuc_scale: 0.381
    nuc_nuc_rc: 15
atom_selection: 'name NUC'

n_trajectories: 1
n_steps: 50_100
report_interval: 100
n_steps_burnin: 100
platform: CPU
friction: 0.01
dt: 0.125
